logging:
  level:
    web: warn
    root: warn

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mvc?useSSL=false
    username: root
    password: Mustafa@93

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  data:
    redis:
      port: 6379
      host: 127.0.0.1

  security:
    user:
      name: mustafa
      password: 123456

server:
  servlet:
    context-path: /mvc
  port: 9080


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always


info:
  app:
    name: MVC test app
    description: application to test spring boot
    version: 1.0.0


test:
  message: Hello from default
